<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            array( 
                'description' =>  "Caramel Coffee with Chocolate",
                'price' => 59.9,
                'image' => "coffee_01",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' => 'Large Cold Coffee with Chocolate',
                'price' => 49.9,
                'image' => "coffee_02",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Cold Latte with Chocolate",
                'price' => 54.9,
                'image' => "coffee_03",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Cold Latte with Chocolate",
                'price' => 54.9,
                'image' => "coffee_04",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Cold Chocolate Milkshake",
                'price' => 54.9,
                'image' => "coffee_05",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Small Hot Chocolate Mocha Coffee",
                'price' => 39.9,
                'image' => "coffee_06",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Hot Chocolate Mocha Coffee",
                'price' => 59.9,
                'image' => "coffee_07",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Hot Cappuccino Coffee",
                'price' => 59.9,
                'image' => "coffee_08",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Medium Hot Mocha Coffee",
                'price' => 49.9,
                'image' => "coffee_09",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Medium Cold Mocha Coffee with Caramel",
                'price' => 49.9,
                'image' => "coffee_10",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Medium Cold Mocha Coffee with Chocolate",
                'price' => 49.9,
                'image' => "coffee_11",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Espresso Coffee",
                'price' => 29.9,
                'image' => "coffee_12",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Cappuccino Coffee with Caramel",
                'price' => 59.9,
                'image' => "coffee_13",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Large Caramel Coffee",
                'price' => 59.9,
                'image' => "coffee_14",
                'category_id' => 1,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donut_01",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Glazed Donuts",
                'price' => 39.9,
                'image' => "donut_02",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Strawberry Donut",
                'price' => 19.9,
                'image' => "donut_03",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Donut with Chocolate Cookie",
                'price' => 19.9,
                'image' => "donut_04",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Strawberry Glass Donut",
                'price' => 19.9,
                'image' => "donut_05",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Glass Donut with Chocolate",
                'price' => 19.9,
                'image' => "donut_06",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate Donut with Extra Chocolate",
                'price' => 19.9,
                'image' => "donut_07",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donut_08",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Vanilla and Chocolate Donuts",
                'price' => 39.9,
                'image' => "donut_09",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 6 Donuts",
                'price' => 69.9,
                'image' => "donut_10",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Varied Donuts",
                'price' => 39.9,
                'image' => "donut_11",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Natural Donut with Chocolate",
                'price' => 19.9,
                'image' => "donut_12",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 3 Chocolate donuts with Sparks",
                'price' => 39.9,
                'image' => "donut_13",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate and Coconut Donut",
                'price' => 19.9,
                'image' => "donut_14",
                'category_id' => 4,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate Cookie Package",
                'price' => 29.9,
                'image' => "cookie_01",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate and Oatmeal Cookie Package",
                'price' => 39.9,
                'image' => "cookie_02",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Vanilla Muffin Pack",
                'price' => 39.9,
                'image' => "cookie_03",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 4 Oatmeal Cookies",
                'price' => 24.9,
                'image' => "cookie_04",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Assorted Butter Cookies",
                'price' => 39.9,
                'image' => "cookie_05",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Fruit-Flavored Cookies",
                'price' => 39.9,
                'image' => "cookie_06",
                'category_id' => 6,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Simple Burger",
                'price' => 59.9,
                'image' => "burger_01",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chicken Burger",
                'price' => 59.9,
                'image' => "burger_02",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chicken and Chili Burger",
                'price' => 59.9,
                'image' => "burger_03",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Cheese and Cucumber Burger",
                'price' => 59.9,
                'image' => "burger_04",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Quarter-Pound Burger",
                'price' => 59.9,
                'image' => "burger_05",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Double Cheese Burger",
                'price' => 69.9,
                'image' => "burger_06",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Special Hot Dog",
                'price' => 49.9,
                'image' => "burger_07",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 2 Hot Dogs",
                'price' => 69.9,
                'image' => "burger_08",
                'category_id' => 2,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pack of 4 Cheese Pay Slices",
                'price' => 69.9,
                'image' => "cake_01",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Special Waffle",
                'price' => 49.9,
                'image' => "cake_02",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Croissants from the House",
                'price' => 39.9,
                'image' => "cake_03",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Cheesecake",
                'price' => 19.9,
                'image' => "cake_04",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate Cake",
                'price' => 29.9,
                'image' => "cake_05",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Chocolate Cake Slice",
                'price' => 29.9,
                'image' => "cake_06",
                'category_id' => 5,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Spicy Double Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_01",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Ham and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_02",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Double Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_03",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Special Pizza from the House",
                'price' => 69.9,
                'image' => "pizza_04",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Meat Pizza",
                'price' => 69.9,
                'image' => "pizza_05",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Hawaiian Pizza",
                'price' => 69.9,
                'image' => "pizza_06",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Bacon Pizza",
                'price' => 69.9,
                'image' => "pizza_07",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Vegetables and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_08",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Pepperoni and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_09",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Olives and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_10",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'description' =>  "Cheese, Ham and Mushrooms Pizza",
                'price' => 69.9,
                'image' => "pizza_11",
                'category_id' => 3,
                'inStock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];
        DB::table('products')->insert($products);
    }
}